### ISSUE TITLE
Please be slightly more explicit about memory ordering

### ISSUE THREAD

**Issue by hboehm** [riscv/riscv-zabha#29]
It seems to me that for completeness, this should explicitly refer to the A and Zacas extension memory ordering specifications, along the following lines:

"The aq and rl bits add acquire-RCsc and release-RCsc annotations to the generated load and store operations, as described in the RVMO description and the A and Zacas extensions."

I think it's pretty clear that this is intended, and hence this isn't a high priority issue, but the document feels incomplete without some such statement.  Arguably rvwmo.adoc already says this, but I think it's actuallly now slightly inconsistent with Zacas for a failing AMOCAS. Thus simply deferring to the rvwmo.adoc section does not seem entirely correct.

**Comment by ved-rivos** [comment]
Thanks. Zabha adds support for byte and halfword operations to the AMOs in A extension and in Zacas extension but does not otherwise change their operations. Agree that adding the following statement can make it explicit:

"Just as for AMOs in the A extension and the Zacas extension, the AMOs provided by the Zabha extension optionally provide release consistency semantics, using the `aq` and `rl` bits, to help implement multiprocessor synchronization."
